fullscreen2(background,2);
fullscreen3(background,3);
fullscreen4(background,4)
pause(1);
fullscreen2(stimL,2);
pause(1);
fullscreen2(stimR,2);
pause(1);
fullscreen2(background,2);
fullscreen3(stimL,3)
pause(1);
fullscreen3(stimR,3)
pause(1);
fullscreen3(background,3)
fullscreen4(background,4)
pause(1);
fullscreen4(stimL,4);
pause(1);
fullscreen4(stimR,4);
pause(1);
fullscreen4(background,4);
pause(1);
closescreen()
